/// poker_game.cairo — StarkPoker (Days 4 + 5)
///
/// State machine:
///   WaitingForPlayer2 → RegisteringKeys → Shuffling → Playing → Showdown → Done
///
/// Day 4: create_game, join_game, register_public_key, submit_masked_deck, submit_shuffle
/// Day 5: submit_partial_decrypt (ZK verified), place_bet, call_bet, fold,
///         advance_to_showdown, reveal_hand, settle, claim_timeout

use starknet::ContractAddress;

// ─── Garaga verifier interface (generated by `garaga gen`) ───────────────────

#[starknet::interface]
pub trait IGroth16Verifier<TContractState> {
    fn verify_groth16_proof_bn254(
        self: @TContractState,
        full_proof_with_hints: Span<felt252>,
    ) -> Result<Span<u256>, felt252>;
}

// ─── Game phase ───────────────────────────────────────────────────────────────

#[allow(starknet::store_no_default_variant)]
#[derive(Drop, Copy, Serde, PartialEq, starknet::Store)]
pub enum GamePhase {
    WaitingForPlayer2, // 0
    RegisteringKeys,   // 1
    Shuffling,         // 2
    Playing,           // 3 — submit PDs + betting
    Showdown,          // 4 — reveal hands + sk
    Done,              // 5
}

// ─── Public interface ─────────────────────────────────────────────────────────

#[starknet::interface]
pub trait IPokerGame<TContractState> {
    // ── Day 4 ────────────────────────────────────────────────────────────────
    fn create_game(ref self: TContractState, ante: u256) -> felt252;
    fn join_game(ref self: TContractState, game_id: felt252);
    fn register_public_key(ref self: TContractState, game_id: felt252, pk_x: u256, pk_y: u256);
    fn submit_masked_deck(ref self: TContractState, game_id: felt252, cards: Span<felt252>);
    fn submit_shuffle(ref self: TContractState, game_id: felt252, cards: Span<felt252>);

    // ── Day 5 — ZK partial decrypt ───────────────────────────────────────────
    /// Submit a Garaga Groth16 proof that pd = sk·C1 and pk = sk·G for one card.
    /// full_proof_with_hints: 2005 elements from garigaProofToCalldata() in TypeScript.
    fn submit_partial_decrypt(
        ref self: TContractState,
        game_id: felt252,
        card_idx: u32,
        pd_x: u256,
        pd_y: u256,
        full_proof_with_hints: Span<felt252>,
    );

    /// Submit a partial decryption without ZK proof (demo / dev mode).
    /// pd = sk · deck[card_idx].c1  — caller asserts this off-chain.
    /// Works in Playing OR Showdown phase.
    fn submit_partial_decrypt_raw(
        ref self: TContractState,
        game_id: felt252,
        card_idx: u32,
        pd_x: u256,
        pd_y: u256,
    );

    // ── Day 5 — Betting ──────────────────────────────────────────────────────
    /// Place a bet.  The other player must call or fold.
    fn place_bet(ref self: TContractState, game_id: felt252, amount: u256);
    /// Match the pending bet.  Advances phase to Showdown.
    fn call_bet(ref self: TContractState, game_id: felt252);
    /// Fold — forfeit the pot to the opponent immediately.
    fn fold(ref self: TContractState, game_id: felt252);
    /// Check (pass).  When both players check → advance to Showdown.
    fn check_action(ref self: TContractState, game_id: felt252);

    // ── Day 5 — Showdown ─────────────────────────────────────────────────────
    /// Reveal your 5-card hand (by deck index).  Phase must be Showdown.
    /// When both players have revealed → settle() is called internally.
    fn reveal_hand(
        ref self: TContractState,
        game_id: felt252,
        c0: u32,
        c1: u32,
        c2: u32,
        c3: u32,
        c4: u32,
    );

    /// Claim the pot after opponent has been inactive for FORFEIT_TIMEOUT_SECS.
    fn claim_timeout(ref self: TContractState, game_id: felt252);

    // ── Views ────────────────────────────────────────────────────────────────
    fn get_game_phase(self: @TContractState, game_id: felt252) -> GamePhase;
    fn get_player1(self: @TContractState, game_id: felt252) -> ContractAddress;
    fn get_player2(self: @TContractState, game_id: felt252) -> ContractAddress;
    fn get_pot(self: @TContractState, game_id: felt252) -> u256;
    fn get_keys_registered(self: @TContractState, game_id: felt252) -> u8;
    fn get_shuffle_step(self: @TContractState, game_id: felt252) -> u8;
    fn get_pk_x(self: @TContractState, game_id: felt252, player: ContractAddress) -> u256;
    fn get_pk_y(self: @TContractState, game_id: felt252, player: ContractAddress) -> u256;
    fn get_deck_felt(self: @TContractState, game_id: felt252, idx: u32) -> felt252;
    fn get_pd_x(
        self: @TContractState, game_id: felt252, player: ContractAddress, card_idx: u32,
    ) -> u256;
    fn get_pd_y(
        self: @TContractState, game_id: felt252, player: ContractAddress, card_idx: u32,
    ) -> u256;
    fn get_pending_bet(self: @TContractState, game_id: felt252) -> u256;
    fn get_checks(self: @TContractState, game_id: felt252) -> u8;
    fn get_hand(
        self: @TContractState, game_id: felt252, player: ContractAddress,
    ) -> (u32, u32, u32, u32, u32);
}

// ─── Contract ─────────────────────────────────────────────────────────────────

#[starknet::contract]
mod PokerGame {
    use super::{
        IPokerGame, GamePhase, IGroth16VerifierDispatcher, IGroth16VerifierDispatcherTrait,
    };
    use starkpoker_contracts::pot_manager::{
        FORFEIT_TIMEOUT_SECS, pull_strk, push_strk,
    };
    use starkpoker_contracts::hand_eval::hand_score;
    use starknet::{ContractAddress, get_caller_address, get_contract_address, get_block_timestamp};
    use starknet::storage::{
        Map, StorageMapReadAccess, StorageMapWriteAccess, StoragePointerReadAccess,
        StoragePointerWriteAccess, StoragePathEntry,
    };
    use core::num::traits::Zero;

    const DECK_SIZE: u32 = 52_u32;
    const CARD_FELTS: u32 = 8_u32;
    const DECK_TOTAL: u32 = 416_u32; // 52 * 8

    // ── Storage ───────────────────────────────────────────────────────────────

    #[storage]
    struct Storage {
        // ── Core game state ───────────────────────────────────────────────────
        game_count: u64,
        phase: Map<felt252, GamePhase>,
        player1: Map<felt252, ContractAddress>,
        player2: Map<felt252, ContractAddress>,
        ante: Map<felt252, u256>,
        pot: Map<felt252, u256>,
        keys_registered: Map<felt252, u8>,
        shuffle_step: Map<felt252, u8>,
        last_action: Map<felt252, u64>,
        // BJJ public keys (u256 per coordinate)
        pk_x: Map<(felt252, ContractAddress), u256>,
        pk_y: Map<(felt252, ContractAddress), u256>,
        // Flat deck: (game_id, flat_idx) → felt252; 8 felts per card
        deck: Map<(felt252, u32), felt252>,

        // ── Partial decrypts (Day 5) ──────────────────────────────────────────
        // pd[game_id][player][card_idx].x / .y
        pd_x: Map<felt252, Map<ContractAddress, Map<u32, u256>>>,
        pd_y: Map<felt252, Map<ContractAddress, Map<u32, u256>>>,

        // ── Betting (Day 5) ───────────────────────────────────────────────────
        // Outstanding bet that the other player must call or fold
        pending_bet: Map<felt252, u256>,
        // Who placed the pending bet (zero = no pending bet)
        bettor: Map<felt252, ContractAddress>,
        // Number of players who have checked this round (0, 1, or 2)
        check_count: Map<felt252, u8>,

        // ── Showdown (Day 5) ─────────────────────────────────────────────────
        // Revealed hands: (game_id, player) → (c0,c1,c2,c3,c4) packed
        // We store them as 5 separate slots for simplicity
        hand_c0: Map<(felt252, ContractAddress), u32>,
        hand_c1: Map<(felt252, ContractAddress), u32>,
        hand_c2: Map<(felt252, ContractAddress), u32>,
        hand_c3: Map<(felt252, ContractAddress), u32>,
        hand_c4: Map<(felt252, ContractAddress), u32>,
        // Bitmask: bit0=p1 revealed, bit1=p2 revealed
        hand_revealed: Map<felt252, u8>,

        // ── Config ────────────────────────────────────────────────────────────
        strk_token: ContractAddress,
        verifier: ContractAddress,
    }

    // ── Events ────────────────────────────────────────────────────────────────

    #[event]
    #[derive(Drop, starknet::Event)]
    enum Event {
        GameCreated: GameCreated,
        PlayerJoined: PlayerJoined,
        KeyRegistered: KeyRegistered,
        DeckSubmitted: DeckSubmitted,
        ShuffleSubmitted: ShuffleSubmitted,
        PartialDecryptSubmitted: PartialDecryptSubmitted,
        BetPlaced: BetPlaced,
        BetCalled: BetCalled,
        PlayerChecked: PlayerChecked,
        PlayerFolded: PlayerFolded,
        HandRevealed: HandRevealed,
        PotAwarded: PotAwarded,
        TimeoutClaimed: TimeoutClaimed,
    }

    #[derive(Drop, starknet::Event)]
    struct GameCreated {
        #[key]
        game_id: felt252,
        player1: ContractAddress,
        ante: u256,
    }
    #[derive(Drop, starknet::Event)]
    struct PlayerJoined {
        #[key]
        game_id: felt252,
        player2: ContractAddress,
    }
    #[derive(Drop, starknet::Event)]
    struct KeyRegistered {
        #[key]
        game_id: felt252,
        player: ContractAddress,
    }
    #[derive(Drop, starknet::Event)]
    struct DeckSubmitted {
        #[key]
        game_id: felt252,
        by: ContractAddress,
    }
    #[derive(Drop, starknet::Event)]
    struct ShuffleSubmitted {
        #[key]
        game_id: felt252,
        by: ContractAddress,
    }
    #[derive(Drop, starknet::Event)]
    struct PartialDecryptSubmitted {
        #[key]
        game_id: felt252,
        player: ContractAddress,
        card_idx: u32,
    }
    #[derive(Drop, starknet::Event)]
    struct BetPlaced {
        #[key]
        game_id: felt252,
        player: ContractAddress,
        amount: u256,
    }
    #[derive(Drop, starknet::Event)]
    struct BetCalled {
        #[key]
        game_id: felt252,
        player: ContractAddress,
    }
    #[derive(Drop, starknet::Event)]
    struct PlayerChecked {
        #[key]
        game_id: felt252,
        player: ContractAddress,
    }
    #[derive(Drop, starknet::Event)]
    struct PlayerFolded {
        #[key]
        game_id: felt252,
        player: ContractAddress,
    }
    #[derive(Drop, starknet::Event)]
    struct HandRevealed {
        #[key]
        game_id: felt252,
        player: ContractAddress,
    }
    #[derive(Drop, starknet::Event)]
    struct PotAwarded {
        #[key]
        game_id: felt252,
        winner: ContractAddress,
        amount: u256,
    }
    #[derive(Drop, starknet::Event)]
    struct TimeoutClaimed {
        #[key]
        game_id: felt252,
        claimer: ContractAddress,
        amount: u256,
    }

    // ── Constructor ───────────────────────────────────────────────────────────

    #[constructor]
    fn constructor(
        ref self: ContractState, strk_token: ContractAddress, verifier: ContractAddress,
    ) {
        self.strk_token.write(strk_token);
        self.verifier.write(verifier);
        self.game_count.write(0_u64);
    }

    // ── External implementation ───────────────────────────────────────────────

    #[abi(embed_v0)]
    impl PokerGameImpl of IPokerGame<ContractState> {
        // ── create_game ───────────────────────────────────────────────────────

        fn create_game(ref self: ContractState, ante: u256) -> felt252 {
            let caller = get_caller_address();
            let count = self.game_count.read();
            let game_id: felt252 = count.into();
            self.game_count.write(count + 1_u64);

            pull_strk(self.strk_token.read(), caller, get_contract_address(), ante);

            self.phase.write(game_id, GamePhase::WaitingForPlayer2);
            self.player1.write(game_id, caller);
            self.ante.write(game_id, ante);
            self.pot.write(game_id, ante);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(GameCreated { game_id, player1: caller, ante });
            game_id
        }

        // ── join_game ─────────────────────────────────────────────────────────

        fn join_game(ref self: ContractState, game_id: felt252) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::WaitingForPlayer2, 'GAME_NOT_OPEN');
            let p1 = self.player1.read(game_id);
            assert(caller != p1, 'CANNOT_PLAY_SELF');

            let ante = self.ante.read(game_id);
            pull_strk(self.strk_token.read(), caller, get_contract_address(), ante);

            self.player2.write(game_id, caller);
            self.pot.write(game_id, ante * 2_u256);
            self.phase.write(game_id, GamePhase::RegisteringKeys);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(PlayerJoined { game_id, player2: caller });
        }

        // ── register_public_key ───────────────────────────────────────────────

        fn register_public_key(
            ref self: ContractState, game_id: felt252, pk_x: u256, pk_y: u256,
        ) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::RegisteringKeys, 'WRONG_PHASE');
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');

            let mask = self.keys_registered.read(game_id);
            let player_bit: u8 = if caller == p1 { 1_u8 } else { 2_u8 };
            assert(mask & player_bit == 0_u8, 'KEY_ALREADY_REGISTERED');

            self.pk_x.write((game_id, caller), pk_x);
            self.pk_y.write((game_id, caller), pk_y);

            let new_mask = mask | player_bit;
            self.keys_registered.write(game_id, new_mask);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(KeyRegistered { game_id, player: caller });

            if new_mask == 3_u8 {
                self.phase.write(game_id, GamePhase::Shuffling);
            }
        }

        // ── submit_masked_deck ────────────────────────────────────────────────

        fn submit_masked_deck(
            ref self: ContractState, game_id: felt252, cards: Span<felt252>,
        ) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::Shuffling, 'WRONG_PHASE');
            assert(caller == self.player1.read(game_id), 'ONLY_PLAYER1');
            assert(self.shuffle_step.read(game_id) == 0_u8, 'DECK_ALREADY_SUBMITTED');
            assert(cards.len() == DECK_TOTAL, 'WRONG_DECK_LEN');

            InternalImpl::store_deck(ref self, game_id, cards);
            self.shuffle_step.write(game_id, 1_u8);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(DeckSubmitted { game_id, by: caller });
        }

        // ── submit_shuffle ────────────────────────────────────────────────────

        fn submit_shuffle(ref self: ContractState, game_id: felt252, cards: Span<felt252>) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::Shuffling, 'WRONG_PHASE');
            assert(caller == self.player2.read(game_id), 'ONLY_PLAYER2');
            assert(self.shuffle_step.read(game_id) == 1_u8, 'P1_MUST_GO_FIRST');
            assert(cards.len() == DECK_TOTAL, 'WRONG_DECK_LEN');

            InternalImpl::store_deck(ref self, game_id, cards);
            self.shuffle_step.write(game_id, 2_u8);
            self.last_action.write(game_id, get_block_timestamp());
            self.phase.write(game_id, GamePhase::Playing);

            self.emit(ShuffleSubmitted { game_id, by: caller });
        }

        // ── submit_partial_decrypt ────────────────────────────────────────────
        // Core ZK innovation: Groth16 proof verifies pd = sk·C1 AND pk = sk·G

        fn submit_partial_decrypt(
            ref self: ContractState,
            game_id: felt252,
            card_idx: u32,
            pd_x: u256,
            pd_y: u256,
            full_proof_with_hints: Span<felt252>,
        ) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::Playing, 'WRONG_PHASE');
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');
            assert(card_idx < DECK_SIZE, 'CARD_IDX_OOB');

            // Retrieve caller's registered public key
            let pk_x = self.pk_x.read((game_id, caller));
            let pk_y = self.pk_y.read((game_id, caller));

            // Reconstruct C1 from flat deck storage
            // Card layout: [c1.x_low, c1.x_high, c1.y_low, c1.y_high, c2.x_low, ...]
            let base: u32 = card_idx * CARD_FELTS;
            let c1_x = u256 {
                low: self.deck.read((game_id, base)).try_into().unwrap(),
                high: self.deck.read((game_id, base + 1_u32)).try_into().unwrap(),
            };
            let c1_y = u256 {
                low: self.deck.read((game_id, base + 2_u32)).try_into().unwrap(),
                high: self.deck.read((game_id, base + 3_u32)).try_into().unwrap(),
            };

            // ── Call Garaga verifier ──────────────────────────────────────────
            let verifier = IGroth16VerifierDispatcher {
                contract_address: self.verifier.read(),
            };
            let result = verifier.verify_groth16_proof_bn254(full_proof_with_hints);
            assert(result.is_ok(), 'PROOF_INVALID');
            let pub_inputs = result.unwrap();

            // Public signals order (from partial_decrypt.circom):
            //   pub[0] = pk.x, pub[1] = pk.y,
            //   pub[2] = c1.x, pub[3] = c1.y,
            //   pub[4] = pd.x, pub[5] = pd.y
            assert(*pub_inputs.at(0) == pk_x, 'PK_X_MISMATCH');
            assert(*pub_inputs.at(1) == pk_y, 'PK_Y_MISMATCH');
            assert(*pub_inputs.at(2) == c1_x, 'C1_X_MISMATCH');
            assert(*pub_inputs.at(3) == c1_y, 'C1_Y_MISMATCH');
            assert(*pub_inputs.at(4) == pd_x, 'PD_X_MISMATCH');
            assert(*pub_inputs.at(5) == pd_y, 'PD_Y_MISMATCH');

            // Store the verified partial decrypt
            self.pd_x.entry(game_id).entry(caller).entry(card_idx).write(pd_x);
            self.pd_y.entry(game_id).entry(caller).entry(card_idx).write(pd_y);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(PartialDecryptSubmitted { game_id, player: caller, card_idx });
        }

        // ── submit_partial_decrypt_raw ────────────────────────────────────────

        fn submit_partial_decrypt_raw(
            ref self: ContractState,
            game_id: felt252,
            card_idx: u32,
            pd_x: u256,
            pd_y: u256,
        ) {
            let caller = get_caller_address();
            let phase = self.phase.read(game_id);
            assert(
                phase == GamePhase::Playing || phase == GamePhase::Showdown,
                'WRONG_PHASE',
            );
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');
            assert(card_idx < DECK_SIZE, 'CARD_IDX_OOB');

            self.pd_x.entry(game_id).entry(caller).entry(card_idx).write(pd_x);
            self.pd_y.entry(game_id).entry(caller).entry(card_idx).write(pd_y);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(PartialDecryptSubmitted { game_id, player: caller, card_idx });
        }

        // ── place_bet ─────────────────────────────────────────────────────────

        fn place_bet(ref self: ContractState, game_id: felt252, amount: u256) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::Playing, 'WRONG_PHASE');
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');
            assert(amount > 0_u256, 'BET_MUST_BE_POSITIVE');
            // Cannot bet if you already have a pending bet out
            assert(self.bettor.read(game_id) != caller, 'ALREADY_BET');
            // Cannot bet if opponent's bet is pending (must call or fold first)
            assert(self.pending_bet.read(game_id) == 0_u256, 'CALL_OR_FOLD_FIRST');

            pull_strk(self.strk_token.read(), caller, get_contract_address(), amount);

            self.pending_bet.write(game_id, amount);
            self.bettor.write(game_id, caller);
            self.pot.write(game_id, self.pot.read(game_id) + amount);
            // Reset check count when a bet is placed
            self.check_count.write(game_id, 0_u8);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(BetPlaced { game_id, player: caller, amount });
        }

        // ── call_bet ──────────────────────────────────────────────────────────

        fn call_bet(ref self: ContractState, game_id: felt252) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::Playing, 'WRONG_PHASE');
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');

            let pending = self.pending_bet.read(game_id);
            assert(pending > 0_u256, 'NO_PENDING_BET');
            assert(self.bettor.read(game_id) != caller, 'CANNOT_CALL_OWN_BET');

            pull_strk(self.strk_token.read(), caller, get_contract_address(), pending);

            self.pot.write(game_id, self.pot.read(game_id) + pending);
            self.pending_bet.write(game_id, 0_u256);
            let zero: ContractAddress = Zero::zero();
            self.bettor.write(game_id, zero);
            self.last_action.write(game_id, get_block_timestamp());

            // Betting round complete → Showdown
            self.phase.write(game_id, GamePhase::Showdown);

            self.emit(BetCalled { game_id, player: caller });
        }

        // ── fold ─────────────────────────────────────────────────────────────

        fn fold(ref self: ContractState, game_id: felt252) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::Playing, 'WRONG_PHASE');
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');

            let winner = if caller == p1 { p2 } else { p1 };
            let pot = self.pot.read(game_id);

            push_strk(self.strk_token.read(), winner, pot);

            self.pot.write(game_id, 0_u256);
            self.phase.write(game_id, GamePhase::Done);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(PlayerFolded { game_id, player: caller });
            self.emit(PotAwarded { game_id, winner, amount: pot });
        }

        // ── check_action ─────────────────────────────────────────────────────

        fn check_action(ref self: ContractState, game_id: felt252) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::Playing, 'WRONG_PHASE');
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');
            // Cannot check if there's a pending bet — must call or fold
            assert(self.pending_bet.read(game_id) == 0_u256, 'MUST_CALL_OR_FOLD');

            let count = self.check_count.read(game_id) + 1_u8;
            self.check_count.write(game_id, count);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(PlayerChecked { game_id, player: caller });

            // Both players checked → Showdown
            if count >= 2_u8 {
                self.phase.write(game_id, GamePhase::Showdown);
            }
        }

        // ── reveal_hand ───────────────────────────────────────────────────────

        fn reveal_hand(
            ref self: ContractState,
            game_id: felt252,
            c0: u32,
            c1: u32,
            c2: u32,
            c3: u32,
            c4: u32,
        ) {
            let caller = get_caller_address();
            assert(self.phase.read(game_id) == GamePhase::Showdown, 'WRONG_PHASE');
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');

            // Guard: each player reveals once
            let revealed = self.hand_revealed.read(game_id);
            let player_bit: u8 = if caller == p1 { 1_u8 } else { 2_u8 };
            assert(revealed & player_bit == 0_u8, 'ALREADY_REVEALED');

            // All cards must be valid deck indices
            assert(c0 < DECK_SIZE && c1 < DECK_SIZE && c2 < DECK_SIZE, 'CARD_IDX_OOB');
            assert(c3 < DECK_SIZE && c4 < DECK_SIZE, 'CARD_IDX_OOB');

            self.hand_c0.write((game_id, caller), c0);
            self.hand_c1.write((game_id, caller), c1);
            self.hand_c2.write((game_id, caller), c2);
            self.hand_c3.write((game_id, caller), c3);
            self.hand_c4.write((game_id, caller), c4);

            let new_revealed = revealed | player_bit;
            self.hand_revealed.write(game_id, new_revealed);
            self.last_action.write(game_id, get_block_timestamp());

            self.emit(HandRevealed { game_id, player: caller });

            // Both players revealed → evaluate and settle
            if new_revealed == 3_u8 {
                InternalImpl::settle(ref self, game_id, p1, p2);
            }
        }

        // ── claim_timeout ─────────────────────────────────────────────────────

        fn claim_timeout(ref self: ContractState, game_id: felt252) {
            let caller = get_caller_address();
            let p1 = self.player1.read(game_id);
            let p2 = self.player2.read(game_id);
            assert(caller == p1 || caller == p2, 'NOT_A_PLAYER');
            // Game must not already be done
            assert(self.phase.read(game_id) != GamePhase::Done, 'GAME_OVER');

            let last = self.last_action.read(game_id);
            assert(
                get_block_timestamp() >= last + FORFEIT_TIMEOUT_SECS, 'NOT_TIMED_OUT',
            );

            let pot = self.pot.read(game_id);
            assert(pot > 0_u256, 'EMPTY_POT');

            push_strk(self.strk_token.read(), caller, pot);

            self.pot.write(game_id, 0_u256);
            self.phase.write(game_id, GamePhase::Done);

            self.emit(TimeoutClaimed { game_id, claimer: caller, amount: pot });
        }

        // ── Views ────────────────────────────────────────────────────────────

        fn get_game_phase(self: @ContractState, game_id: felt252) -> GamePhase {
            self.phase.read(game_id)
        }
        fn get_player1(self: @ContractState, game_id: felt252) -> ContractAddress {
            self.player1.read(game_id)
        }
        fn get_player2(self: @ContractState, game_id: felt252) -> ContractAddress {
            self.player2.read(game_id)
        }
        fn get_pot(self: @ContractState, game_id: felt252) -> u256 {
            self.pot.read(game_id)
        }
        fn get_keys_registered(self: @ContractState, game_id: felt252) -> u8 {
            self.keys_registered.read(game_id)
        }
        fn get_shuffle_step(self: @ContractState, game_id: felt252) -> u8 {
            self.shuffle_step.read(game_id)
        }
        fn get_pk_x(self: @ContractState, game_id: felt252, player: ContractAddress) -> u256 {
            self.pk_x.read((game_id, player))
        }
        fn get_pk_y(self: @ContractState, game_id: felt252, player: ContractAddress) -> u256 {
            self.pk_y.read((game_id, player))
        }
        fn get_deck_felt(self: @ContractState, game_id: felt252, idx: u32) -> felt252 {
            assert(idx < DECK_TOTAL, 'IDX_OUT_OF_RANGE');
            self.deck.read((game_id, idx))
        }
        fn get_pd_x(
            self: @ContractState, game_id: felt252, player: ContractAddress, card_idx: u32,
        ) -> u256 {
            self.pd_x.entry(game_id).entry(player).entry(card_idx).read()
        }
        fn get_pd_y(
            self: @ContractState, game_id: felt252, player: ContractAddress, card_idx: u32,
        ) -> u256 {
            self.pd_y.entry(game_id).entry(player).entry(card_idx).read()
        }
        fn get_pending_bet(self: @ContractState, game_id: felt252) -> u256 {
            self.pending_bet.read(game_id)
        }
        fn get_checks(self: @ContractState, game_id: felt252) -> u8 {
            self.check_count.read(game_id)
        }
        fn get_hand(
            self: @ContractState, game_id: felt252, player: ContractAddress,
        ) -> (u32, u32, u32, u32, u32) {
            (
                self.hand_c0.read((game_id, player)),
                self.hand_c1.read((game_id, player)),
                self.hand_c2.read((game_id, player)),
                self.hand_c3.read((game_id, player)),
                self.hand_c4.read((game_id, player)),
            )
        }
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    #[generate_trait]
    impl InternalImpl of InternalTrait {
        /// Write 416 felt252s from `cards` into flat deck storage for `game_id`.
        fn store_deck(ref self: ContractState, game_id: felt252, cards: Span<felt252>) {
            let mut i: u32 = 0_u32;
            loop {
                if i >= DECK_TOTAL {
                    break;
                }
                self.deck.write((game_id, i), *cards.at(i));
                i += 1_u32;
            };
        }

        /// Evaluate both hands and transfer pot to winner.
        /// Called automatically after both players have called reveal_hand.
        fn settle(ref self: ContractState, game_id: felt252, p1: ContractAddress, p2: ContractAddress) {
            // Read p1's hand
            let p1c0 = self.hand_c0.read((game_id, p1));
            let p1c1 = self.hand_c1.read((game_id, p1));
            let p1c2 = self.hand_c2.read((game_id, p1));
            let p1c3 = self.hand_c3.read((game_id, p1));
            let p1c4 = self.hand_c4.read((game_id, p1));

            // Read p2's hand
            let p2c0 = self.hand_c0.read((game_id, p2));
            let p2c1 = self.hand_c1.read((game_id, p2));
            let p2c2 = self.hand_c2.read((game_id, p2));
            let p2c3 = self.hand_c3.read((game_id, p2));
            let p2c4 = self.hand_c4.read((game_id, p2));

            let score1 = hand_score(p1c0, p1c1, p1c2, p1c3, p1c4);
            let score2 = hand_score(p2c0, p2c1, p2c2, p2c3, p2c4);

            // Higher score wins; p1 wins on tie (house rule for simplicity)
            let winner = if score1 >= score2 { p1 } else { p2 };

            let pot = self.pot.read(game_id);
            push_strk(self.strk_token.read(), winner, pot);

            self.pot.write(game_id, 0_u256);
            self.phase.write(game_id, GamePhase::Done);

            self.emit(PotAwarded { game_id, winner, amount: pot });
        }
    }
}
